### PR TITLE
Draft of publishing policy

### PR DESCRIPTION
**Pull request by Carreau**
cc @minrk @SylvainCorlay @ellisonbg @damianavila

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Opened a PR to your PR changing the wording of the license requirement for code examples.

**Comment by Carreau** [comment]
Thanks.

**Comment by SylvainCorlay** [comment]
:+1:

**Comment by minrk** [comment]
Thanks, @Carreau!

**Comment by Carreau** [comment]
Sorry I made a mistake with my branches ans screwed up master today unmerging that. I'll fix it by force pushing on master.

**Comment by Carreau** [comment]
Can you review [this page](http://ipython.org/books_policy.html#books-policy) that was missing from this PR and was linked as the bottom of this PR but missing.

**Comment by damianavila** [comment]
> Can you review this page that was missing from this PR and was linked as the bottom of this PR but missing.

I think it is OK as well as this PR. Thanks @Carreau.

**Pull request merged**
