### PR TITLE
Create LICENSE

### LINKED ISSUE #133: Add LICENSE

### PR DESCRIPTION
**Pull request by fm75**
Fixes #133

### CODE REVIEW

**Comment by jzf2101** [comment]
Could someone confirm we can have a license on the website?

**Comment by takluyver** [comment]
We can, but I think it should be a content license (like the CC family) rather than a code license like BSD.

**Comment by fm75** [comment]
@jzf2101 - You are probably right about the content license. We did many PRs as part of a sprint after jupytercon. I think it would be best to let Jessica work out the details on this and the similar PRs.

**Comment by Carreau** [comment]
> We can, but I think it should be a content license (like the CC family) rather than a code license like BSD.

Also if the license have a date it should likely not be 2017 but the first date the website was released.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. Seems like we reached consensus here that BSD 3-clause is not the license we'd want to use for the website assets.

Thanks everyone and happy hacking! :bowtie:

**Pull request closed without merging**
