### PR TITLE
Announce 5.1, update home page and docs page

### PR DESCRIPTION
**Pull request by takluyver**
I went to update the website after making the 5.1 release, and did a few other bits of improvement:

- Cleaned up old announcements from the homepage.
- Removed unused link targets
- Reworked the docs landing page to be clearer and provide more useful links to other pieces.
- Got rid of some Sphinx warnings

Ping @Carreau @willingc

### CODE REVIEW

**Comment by Carreau** [comment]
+1. 

As it removes some link of some of our grants, I'd like the +1 of @fperez  or @ellisonbg

**Comment by willingc** [comment]
@Carreau The links to the grants are only removed from the Announcements section of `index.rst` and are still available in `news.rst`.

I would recommend merging this PR. A separate PR could handle any items from `news.rst` that Brian or Fernando wish to keep in the Announcements section.

+1 to merging. Thanks @takluyver!

**Comment by fperez** [comment]
Agreed, Announcements is meant to stay small and recent, and we roll anything old over to the reverse-chronological news file.  Since these particular items are already in "news", this is just regular announcements cleanup.

+1 to merge as-is, and I don't see a need to move anything old back into announcements.

**Comment by fperez** [comment]
news should be a complete log, and it goes way back to 2006, which is fine.  As long as whenever we drop something from announcements we move it over to news (or check it was already there), we can keep it pruned.

**Comment by Carreau** [comment]
Ah! Thanks all, not sure how I missed all that!

Thanks again Thomas for getting 5.1 out!

I'll merge once i'm on my computer.

**Comment by willingc** [comment]
@Carreau No problem. I missed it too on my visual review of the code.  I didn't see it until I actually loaded up everything locally. Thanks for merging :D

And thanks @takluyver and the whole team 🎉

**Comment by Carreau** [comment]
Oops seem like we forgot to merge that. 

Thanks @takluyver

**Pull request merged**
